---
- hosts: wordpress
  tasks:
  - name: update packages
    become: yes
    apt: update_cache=yes

  - name: prerequisites1
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: prerequisites2
    become: yes
    apt: 
      pkg:
       - apache2
       - mysql-common
       - php7.3-mysql
       - php7.3
       - libapache2-mod-php7.3
       - python-mysqldb
       - php7.3-gd
       - php7.3-ssh2
       - vsftpd
