---
- hosts: wordpress
  become: yes
  tasks:
  - name: update packages 
    apt: update_cache=yes

  - name: prerequisites1
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: prerequisites2
    apt: 
      pkg:
       - apache2
       - php7.3-mysql
       - php7.3
       - libapache2-mod-php7.3
       - php7.3-gd
       - php7.3-ssh2
       - vsftpd
