---
- hosts: wordpress
  become: yes
  vars:
    theDomain: "testing"

  tasks:
  - name: update packages 
    apt: update_cache=yes

  - name: Ubuntu install - prerequisites1
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Ubuntu install - prerequisites2 
    apt: 
      pkg:
       - apache2
       - php
       - libapache2-mod-php
       - php-mysql
       - php-xml
       - php-curl
       - vsftpd
       - openssl

  - name: enable Apache ssl module
    apache2_module: 
      name: ssl
      state: present

  - name: generate self signed certificate
      shell: |
        cd /etc/apache2 
        openssl genrsa -out {{theDomain}}.key 1024
        openssl req -new x509 -days 90 -key {{theDomain}}.key -out {{theDomain}}.crt -subj "/C=RO/L=Iasi/O={{theDomain}}/CN=www.{{theDomain}}.eu"
