---
- hosts: wordpress
  vars:
    wp_mysql_db: "wordpress"
    wp_mysql_user: "wordpress"
    wp_mysql_password: "admin"

  tasks:
  - name: create mysql auth file
    become: yes
    template:
     src: my.cnf.j2
     dest: "~/.my.cnf"
     mode: 0640

  - name: create mysql user
    mysql_user:
        name: "{{wp_mysql_user}}"
        password: "{{wp_mysql_password}}"
        
  - name: create mysql db
    mysql_db:
        name: "{{wp_mysql_db}}"
        state: present

